name: CI/CD Pipeline - Payment App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    # 1. Checkout source code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker login to Nexus
    - name: Docker login to Nexus
      shell: bash
      run: |
        echo "${{ secrets.NEXUS_PASSWORD }}" | docker login http://${{ secrets.NEXUS_REPO_URL }} -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

    # 3. Build Docker images
    - name: Build Docker images
      run: |
        docker build -t payment-frontend ./frontend
        docker build -t auth-service ./backend/auth_service
        docker build -t payment-service ./backend/payment_service

    # 4. Tag and Push to Nexus
    - name: Push Docker Images to Nexus
      run: |
        docker tag payment-frontend ${{ secrets.NEXUS_REPO_URL }}/payment-frontend:latest
        docker tag auth-service ${{ secrets.NEXUS_REPO_URL }}/auth-service:latest
        docker tag payment-service ${{ secrets.NEXUS_REPO_URL }}/payment-service:latest

        docker push ${{ secrets.NEXUS_REPO_URL }}/payment-frontend:latest
        docker push ${{ secrets.NEXUS_REPO_URL }}/auth-service:latest
        docker push ${{ secrets.NEXUS_REPO_URL }}/payment-service:latest

    # 5. Deploy using docker-compose on same EC2
    - name: Deploy Application with Docker Compose
      run: |
        cd /home/ubuntu/payment_app   # adjust this path if needed
        docker compose down
        docker compose pull
        docker compose up -d --build
